name: TelegramChat
main: org.leining.TelegramChat.Main
version: 1.1
authors: [blasphemy@github]
description: Brings minecraft chat to Telegram!
commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken